#!/bin/bash
##########################
##########################
##########################
##########################
##########github.com/m41k#
##########################
##
##
##
##
##
#//maik.alberto@hotmail.com
#//netcat-openbsd - required
#-----------------------------------------#
# CONFIGURAÇÃO                            #  
#-----------------------------------------#
#PORTA - SCREENDOR
 APORT=401
#PORTA PROTEGIDA - SERVICE PORT
 SPORT=6070
#ARQUIVOS PARA COMPARACAO DA CHAVE
 ALIST=/tmp/alist
 CLIST=/tmp/clist
#TEMPO PARA ENTRAR COM A CHAVE
 ATIME=5
#TEMPO LIBERAÇÃO DO SERVIÇO
 STIME=10
#FLAG
 FLAG=KURUPIRA
#CHAVE - PALAVRA PASSE(MD5)
#PASS=s3nha
 SPASS=db2c158f319a22a8e32a4979905b2b44
#Chain
 CHAIN=SREENDOOR
#-----------------------------------------#
#IPTABLES
#-----------------------------------------#
 iptables -F $CHAIN 2> /dev/null
 iptables -N $CHAIN 2> /dev/nul
 iptables -A $CHAIN -p tcp --dport $SPORT -j REJECT

#MATANDO POSSIVEL PROCESSO PERDIDO
 npid=`ps -ax | grep "\bnc -d -l -w$ATIME -p$APORT" | cut -c 1-6`
 kill -9 $npid 2>/dev/null

 echo > $ALIST
 echo > $CLIST

 LACO=1
 RODA=0

while [ $LACO = 1 ];
   do
     fuser -sn tcp $APORT
     RODA=$?
     if  [ "$RODA" -eq "1" ]; then
         nc -d -l -w$ATIME -p$APORT > $ALIST &
     fi
     tail -n 1 $ALIST | md5sum | cut -d " " -f1 > $CLIST
     grep '\b'$SPASS'\b' $CLIST
     LACO=$?
  done

#-----------------------------------------#
#INCLUSÃO REGRAS IPTABLES
#-----------------------------------------#
 iptables -I $CHAIN 1 -p tcp --dport $SPORT -j ACCEPT

#LIMPANDO ARQUIVOS
 echo > $ALIST
 echo > $CLIST

#SIMULANDO SERVIÇO - POSSIVEL VISUALIZAR NO BROWSER
#for i in $(seq $STIME); do echo $FLAG | nc -l $SPORT | sleep 1; done
 for i in $(seq $STIME); do
   #echo $i
   echo $FLAG | nc -l $SPORT -w$STIME | sleep 1;
 done

#SLEEP PARA DAEMON
 #sleep $STIME

#-----------------------------------------#
#REMOÇÃO REGRAS IPTABLES
#-----------------------------------------#
 iptables -D $CHAIN -p tcp --dport $SPORT -j ACCEPT

#Let's go again
 $0
